---
- name: "Ensure LDAP management container image is pulled"
  community.docker.docker_image:
    name: "{{ ldap_management_container_image_reference }}"
    force_source: "{{ ldap_management_container_pull }}"
    source: "pull"
    state: "present"
  when: "ldap_management_container_enabled | bool"
  tags: ["prepare", "prepare-ldap"]

- name: "Ensure LDAP management container is started"
  community.docker.docker_container:
    name: "{{ ldap_management_container_name }}"
    image: "{{ ldap_management_container_image_reference }}"
    ports: "{{ ldap_management_container_ports }}"
    labels: "{{ ldap_management_container_labels_complete }}"
    env: "{{ ldap_management_container_env }}"
    restart_policy: "unless-stopped"
    recreate: "{{ ldap_management_container_recreate }}"
    pull: "{{ ldap_management_container_pull }}"
    healthcheck:
      test: >-
        [ $(pgrep -u www-data -c -f /usr/sbin/apache2) -gt 0 ]
        || exit 1
  when: "ldap_management_container_enabled | bool"
  tags: ["deploy", "deploy-ldap"]

- name: "Ensure LDAP management container is absent"
  community.docker.docker_container:
    name: "{{ ldap_management_container_name }}"
    state: "absent"
  when: "not ldap_management_container_enabled | bool"
  tags: ["deploy", "deploy-ldap"]
