---
postgresql_connection:
  login_host: >-
    {{
      postgresql_socket_path
      if postgresql_connect_socket
      else (
        postgresql_container.container.NetworkSettings.IPAddress
        if postgresql_host_port is undefined
        else "127.0.0.1"
      )
    }}
  login_port: >-
    {{
      postgresql_host_port if postgresql_host_port is defined and not postgresql_connect_socket
      else "5432"
    }}
  login_password: "{{ postgresql_superuser_password }}"

postgresql_container_data_dir: "/var/lib/postgresql/data"
postgresql_container_socket_dir: "/var/run/postgresql"

postgresql_container_volumes_base:
  - "{{ postgresql_data_path }}:{{ postgresql_container_data_dir }}:z"
  - "{{ postgresql_config_path }}/pg_hba.conf:{{ postgresql_container_data_dir }}/pg_hba.conf:ro"
  - "{{ postgresql_config_path }}/pg_ident.conf:{{ postgresql_container_data_dir }}/pg_ident.conf:ro"
  - "{{ postgresql_config_path }}/postgresql-passwd:/etc/passwd:ro"
postgresql_container_volumes_complete: >-
  {{ postgresql_container_volumes_base
  + ([postgresql_socket_path + ':' + postgresql_container_socket_dir + ':z']
    if postgresql_connect_socket else [])
  }}

postgresql_container_init_volumes:
  - "{{ postgresql_data_path }}:{{ postgresql_container_data_dir }}:z"
  - "{{ postgresql_socket_path }}:{{ postgresql_container_socket_dir }}:z"
  - "{{ postgresql_config_path }}/postgresql-passwd:/etc/passwd:ro"

postgresql_container_labels_base:
  version: "{{ postgresql_container_version }}"
postgresql_container_labels_complete: >-
  {{ postgresql_container_labels_base | combine(postgresql_container_labels) }}
