---
lego_base_path: "/opt/lego"
lego_certificate_store: "{{ lego_base_path }}/certificates"
lego_certificate_store_user: "{{ lego_user_res.uid | default(lego_user) }}"
lego_certificate_store_group: "{{ lego_user_res.group | default(lego_user) }}"
lego_certificate_store_mode: "0750"
lego_systemd_path: "/etc/systemd/system"
lego_version: "4.5.2"
lego_system_type: "linux"
lego_system_arch: "amd64"
lego_executable: "{{ lego_base_path }}/lego"
lego_account_base_path: "{{ lego_base_path }}/accounts"
lego_cap_net_bind_service: true

lego_enable_metrics_textfile: false

lego_source_server_domain: "github.com"
lego_source_url: >-2
  https://{{
    lego_source_server_domain
  }}/go-acme/lego/releases/download/v{{
    lego_version
  }}/lego_v{{
    lego_version
  }}_{{
    lego_system_type
  }}_{{
    lego_system_arch
  }}.tar.gz
lego_source_checksum_url: >-2
  sha256:https://{{
    lego_source_server_domain
  }}/go-acme/lego/releases/download/v{{
    lego_version
  }}/lego_{{
    lego_version
  }}_checksums.txt
lego_source_url_http_username: ~
lego_source_url_http_password: ~

lego_check_version_cmd: >-2
  test -e {{ lego_executable }} && {{ lego_executable }} --version

lego_user: "lego"
lego_timer_on_boot: ~
lego_timer_on_calendar: "*-*-* 00,12:00:00"
lego_timer_interval: ~
lego_timer_accuracy: ~
lego_timer_random_delay: 43200
lego_timer_persistent: true

lego_certificate: ~
lego_letsencrypt_environment: "staging"

lego_challenge:
  type: "http"

lego_letsencrypt_servers:
  prod: "https://acme-v02.api.letsencrypt.org/directory"
  staging: "https://acme-staging-v02.api.letsencrypt.org/directory"

lego_tasks:
  playbook: "run"
  systemd: "renew"

lego_acme_account_defaults:
  email: "{{ lego_certificate.email }}"
  registration:
    body:
      status: "valid"
      contact:
        - "mailto:{{ lego_certificate.email }}"

lego_certificate_renewal_days: 30
lego_configuration_default_key_type: "ec256"

lego_configuration_defaults:
  command_parameters:
    global:
      server: "{{ lego_letsencrypt_servers[lego_letsencrypt_environment] }}"
      accept-tos: true
      email: "{{ lego_certificate.email }}"
      path: "{{ lego_base_path }}"
      key-type: "{{ lego_configuration_default_key_type }}"
    run: {}
    renew:
      days: "{{ lego_certificate_renewal_days }}"
  environment: {}

lego_install_dependencies: false
lego_dependencies:
  Debian:
    "11":
      - "python3-cryptography"
    all:
      - "python3-cryptography"
