---

redis_version: "6.2.1"
redis_user: "{{ redis_prefix }}redis"
redis_basepath: "/opt/redis"
redis_data_dir: "{{ redis_basepath }}/{{ redis_prefix }}data"
redis_config_dir: "{{ redis_basepath }}/{{redis_prefix }}config"
redis_config_file: "{{ redis_config_dir }}/redis.conf"
redis_secret: ~

# Overwrite per-instance to be able to run many instances on the same host
# prefix should be sth like 'matrix_', modifies mapped directories, container name and uer
redis_prefix: ""

redis_docker_labels: {}
redis_docker_configpath: "/usr/local/etc/redis/redis.conf"
redis_docker_image: "docker.io/library/redis:{{ redis_docker_tag }}"
redis_docker_tag: "{{ redis_version }}-alpine"
redis_docker_container_name: "{{ redis_prefix }}redis"
redis_docker_ports: [ "6379:6379" ]
redis_docker_volumes:
  - "{{ redis_data_dir }}:/data"
  - "{{ redis_config_file }}:{{ redis_docker_configpath }}"
